services:
  - type: web
    name: boat-rental-system
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      npm install
      npm run build
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://boat-rental-system.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: boat-rental-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: boat-rental-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: boat-rental-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: boat-rental-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: boat-rental-db
          property: password

databases:
  - name: boat-rental-db
    databaseName: boat_rental
    user: boat_rental_user